export const platformProfiles = {
  linkedin: {
    id: "linkedin",
    label: "LinkedIn",
    audienceExpectation: "credible, useful, specific, professional",
    voice: "calm, informed, human, experience-backed",
    bestFormats: ["lesson", "case study", "field note", "process breakdown"],
    structureRules: [
      "Lead with the insight or problem.",
      "Keep humor controlled and earned.",
      "Give the reader a takeaway, not just a vibe.",
    ],
    ctaStyle: "Invite discussion, feedback, or reflection.",
    linkTolerance: "medium",
    emojiTolerance: "low",
    humorTolerance: "low",
    avoid: ["sloppy irony", "too many in-jokes", "unearned hype"],
    openerPatterns: [
      "A short professional tension statement",
      "A lesson learned from real work",
      "A surprising but credible observation",
    ],
    notes: [
      "Best when the post sounds competent before it sounds playful.",
      "Use proof, specifics, and working language.",
    ],
    sourceNotes: ["LinkedIn creator guidance and professional posting norms."],
  },
  x: {
    id: "x",
    label: "X",
    audienceExpectation: "fast, timely, punchy, identity-clear",
    voice: "sharp, concise, opinionated, high signal",
    bestFormats: ["take", "build update", "short thread", "commentary"],
    structureRules: [
      "Front-load the hook.",
      "One post should carry one main point.",
      "Make the first line do real work.",
    ],
    ctaStyle: "Reply, react, quote, or click through.",
    linkTolerance: "medium",
    emojiTolerance: "medium",
    humorTolerance: "high",
    avoid: ["burying the point", "generic brand copy", "overexplaining"],
    openerPatterns: [
      "A strong opinion",
      "A weird but clear observation",
      "A compact build-in-public update",
    ],
    notes: [
      "High tolerance for punchy language if the point is clear.",
      "Speed and clarity matter more than polish.",
    ],
    sourceNotes: ["X professional account and creator-product guidance."],
  },
  facebook: {
    id: "facebook",
    label: "Facebook",
    audienceExpectation: "broader, conversational, personality-friendly",
    voice: "friendly, story-first, warm, lightly playful",
    bestFormats: ["anecdote", "casual update", "link post", "community question"],
    structureRules: [
      "Explain context before the ask.",
      "Make the human angle obvious.",
      "Keep it more relaxed than LinkedIn.",
    ],
    ctaStyle: "Comment, share, react, or click through.",
    linkTolerance: "high",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["hard ad tone", "dense technical blocks with no story"],
    openerPatterns: [
      "A casual story setup",
      "A familiar problem statement",
      "A conversational observation",
    ],
    notes: ["Needs tuning against your own page data."],
    sourceNotes: ["Inference-driven profile based on broad platform behavior."],
  },
  instagram: {
    id: "instagram",
    label: "Instagram",
    audienceExpectation: "visual-first, emotionally immediate, creator-forward",
    voice: "concise, personal, vivid",
    bestFormats: ["carousel", "short narrative", "behind-the-scenes", "quick tip"],
    structureRules: [
      "The caption should support the visual asset.",
      "The first line should earn the expand tap.",
      "Keep paragraph rhythm clean.",
    ],
    ctaStyle: "Save, share, comment, DM, or watch.",
    linkTolerance: "low",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["link-dependent messaging", "heavy technical explanation with no visual payoff"],
    openerPatterns: [
      "A bold visual hook",
      "A personal one-line setup",
      "A quick promise of value",
    ],
    notes: ["Caption quality matters, but the asset still carries the post."],
    sourceNotes: ["Instagram creator guidance patterns plus format norms."],
  },
  threads: {
    id: "threads",
    label: "Threads",
    audienceExpectation: "conversational, current, casual-smart",
    voice: "thoughtful but unforced",
    bestFormats: ["perspective post", "discussion starter", "short observation"],
    structureRules: [
      "Sound like a person talking, not a company publishing.",
      "Invite reply more than click.",
      "Keep the friction low.",
    ],
    ctaStyle: "Ask what others think or have seen.",
    linkTolerance: "low",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["hard-sell framing", "rigid launch-copy"],
    openerPatterns: [
      "A current observation",
      "A reflective thought",
      "A conversation-starting opinion",
    ],
    notes: ["Good fit for smart, lightweight commentary."],
    sourceNotes: ["Threads conversation/community product direction."],
  },
  pinterest: {
    id: "pinterest",
    label: "Pinterest",
    audienceExpectation: "searchable, practical, evergreen, save-worthy",
    voice: "clear, useful, benefit-led",
    bestFormats: ["idea pin", "visual guide", "checklist", "template graphic"],
    structureRules: [
      "Title the benefit clearly.",
      "Align the copy with a searchable use case.",
      "Prefer evergreen value when possible.",
    ],
    ctaStyle: "Save this, try this, click for the full guide.",
    linkTolerance: "high",
    emojiTolerance: "low",
    humorTolerance: "low",
    avoid: ["vague captions", "jokes without utility"],
    openerPatterns: [
      "A clear benefit promise",
      "A searchable problem statement",
      "A direct template or idea hook",
    ],
    notes: ["Useful beats clever."],
    sourceNotes: ["Pinterest business/help positioning around discoverable visual content."],
  },
  reddit: {
    id: "reddit",
    label: "Reddit",
    audienceExpectation: "subreddit-specific value, authenticity, anti-spam",
    voice: "direct, plain, transparent, context-aware",
    bestFormats: ["answer", "build log", "problem-solution writeup", "relevant story"],
    structureRules: [
      "Respect subreddit norms first.",
      "Add value before mentioning the product.",
      "Disclose context when relevant.",
    ],
    ctaStyle: "Discussion-first, minimal direct CTA.",
    linkTolerance: "low",
    emojiTolerance: "low",
    humorTolerance: "medium",
    avoid: ["marketing tone", "copy-paste blasts", "vague self-promotion"],
    openerPatterns: [
      "A specific problem statement",
      "A relevant personal build note",
      "A concrete answer to a common question",
    ],
    notes: ["The subreddit is the real platform."],
    sourceNotes: ["Reddit help policies on promotions and authenticity."],
  },
  devto: {
    id: "devto",
    label: "Dev.to",
    audienceExpectation: "technical, practical, readable",
    voice: "dev-friendly, transparent, educational",
    bestFormats: ["tutorial", "lesson learned", "architecture note", "build log"],
    structureRules: [
      "Use substance.",
      "Prioritize clarity over hype.",
      "Make the post useful even without the product.",
    ],
    ctaStyle: "Read more, try it, or give feedback.",
    linkTolerance: "medium",
    emojiTolerance: "low",
    humorTolerance: "medium",
    avoid: ["shallow promo copy", "buzzword stuffing"],
    openerPatterns: [
      "A technical problem setup",
      "A lesson learned",
      "A concrete implementation story",
    ],
    notes: ["Technical value has to come first."],
    sourceNotes: ["Article-first developer publishing norms."],
  },
  hashnode: {
    id: "hashnode",
    label: "Hashnode",
    audienceExpectation: "technical depth and thoughtful writing",
    voice: "professional, builder-focused, polished",
    bestFormats: ["engineering essay", "walkthrough", "technical breakdown"],
    structureRules: [
      "Go deeper than a feed post.",
      "Use stronger structure than X or Threads.",
      "Value first, promotion second.",
    ],
    ctaStyle: "Feedback, reading, or product context after value.",
    linkTolerance: "medium",
    emojiTolerance: "low",
    humorTolerance: "low",
    avoid: ["meme-heavy copy", "shallow launch noise"],
    openerPatterns: [
      "A clear technical promise",
      "An engineering insight",
      "A structured deep-dive opener",
    ],
    notes: ["Closer to a technical blog than a social feed."],
    sourceNotes: ["Platform and community norms."],
  },
  producthunt: {
    id: "producthunt",
    label: "Product Hunt",
    audienceExpectation: "launch clarity, authenticity, maker presence",
    voice: "crisp, excited, credible",
    bestFormats: ["launch description", "maker comment", "feature summary"],
    structureRules: [
      "Explain what it is.",
      "Explain who it is for.",
      "Explain why it matters now.",
    ],
    ctaStyle: "Try it, leave feedback, ask questions.",
    linkTolerance: "high",
    emojiTolerance: "low",
    humorTolerance: "low",
    avoid: ["fake scarcity", "vague hype", "posting then disappearing"],
    openerPatterns: [
      "What it is in one line",
      "A maker-led intro",
      "A use-case-led launch opener",
    ],
    notes: ["Strong first comment matters."],
    sourceNotes: ["Product Hunt launch guide and posting help."],
  },
  tumblr: {
    id: "tumblr",
    label: "Tumblr",
    audienceExpectation: "culture-aware, expressive, niche-friendly",
    voice: "voicey, stylized, community-literate",
    bestFormats: ["mood post", "visual/editorial post", "subculture commentary"],
    structureRules: [
      "Let the voice breathe.",
      "Use tags intentionally.",
      "Account for community and link-spam moderation.",
    ],
    ctaStyle: "Notes, reblogs, replies.",
    linkTolerance: "medium",
    emojiTolerance: "medium",
    humorTolerance: "high",
    avoid: ["sterile corporate copy", "obvious spammy links"],
    openerPatterns: [
      "A mood-first line",
      "A niche observation",
      "A stylized joke with context",
    ],
    notes: ["Useful weirdness is allowed; generic brand voice is not."],
    sourceNotes: ["Tumblr support updates on communities and link-spam limits."],
  },
  discord: {
    id: "discord",
    label: "Discord",
    audienceExpectation: "in-room update, not broadcast ad copy",
    voice: "direct, brief, human, situational",
    bestFormats: ["update", "changelog", "ask", "resource drop"],
    structureRules: [
      "Assume ongoing context.",
      "Avoid bloated intros.",
      "Write like you are dropping into a room, not a feed.",
    ],
    ctaStyle: "React, reply, test, or click if useful.",
    linkTolerance: "medium",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["polished broadcast language"],
    openerPatterns: [
      "Quick update",
      "Direct ask",
      "Useful drop with minimal setup",
    ],
    notes: ["Channel culture matters more than generic platform rules."],
    sourceNotes: ["Usage-pattern inference; tune per server."],
  },
  kofi: {
    id: "kofi",
    label: "Ko-fi",
    audienceExpectation: "supporter relationship, creator warmth",
    voice: "personal, grateful, gently promotional",
    bestFormats: ["update note", "supporter offer", "commission post", "behind-the-scenes"],
    structureRules: [
      "Explain what supporters get.",
      "Make the relationship obvious.",
      "Reward directness over funnel-speak.",
    ],
    ctaStyle: "Support, commission, follow, unlock.",
    linkTolerance: "high",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["aggressive funnel-speak"],
    openerPatterns: [
      "A warm update",
      "A creator note",
      "A direct support or commission offer",
    ],
    notes: ["Support context should feel relational, not corporate."],
    sourceNotes: ["Creator-support product norms."],
  },
  amazon: {
    id: "amazon",
    label: "Amazon",
    audienceExpectation: "transactional clarity",
    voice: "plain, confidence-building, benefit-first",
    bestFormats: ["product descriptor", "utility summary"],
    structureRules: [
      "Reduce ambiguity quickly.",
      "Focus on fit and use case.",
      "Keep the copy clean and direct.",
    ],
    ctaStyle: "Buy, compare, learn more.",
    linkTolerance: "high",
    emojiTolerance: "low",
    humorTolerance: "low",
    avoid: ["social-style chaos", "inside jokes"],
    openerPatterns: [
      "A use-case statement",
      "A fit-for-who opener",
      "A practical benefit line",
    ],
    notes: ["This is not a social voice."],
    sourceNotes: ["Marketplace-intent inference."],
  },
  onlyfans: {
    id: "onlyfans",
    label: "OnlyFans",
    audienceExpectation: "exclusivity, boundary clarity, relationship and reward",
    voice: "brand-specific",
    bestFormats: ["teaser", "reward framing", "membership offer"],
    structureRules: [
      "Customize heavily per creator brand.",
      "Keep boundaries explicit.",
      "Use relationship cues intentionally.",
    ],
    ctaStyle: "Subscribe, unlock, message, view.",
    linkTolerance: "high",
    emojiTolerance: "medium",
    humorTolerance: "medium",
    avoid: ["generic default prompts"],
    openerPatterns: [
      "A custom teaser line",
      "A reward-led opener",
      "A direct exclusive-content hook",
    ],
    notes: ["Should remain highly customized."],
    sourceNotes: ["Creator-specific workflow rather than generic automation."],
  },
};

export function getPlatformProfile(platformId) {
  if (!platformId) return null;
  return platformProfiles[String(platformId).toLowerCase()] || null;
}
