export const productProfiles = [
  {
    id: "postpunk-core",
    label: "PostPunk Core",
    lifecycleStatus: "in-progress",
    category: "Devtools",
    productType: "Local-first social automation tool",
    audience: "indie creators, solo founders, and weird-tool builders",
    brandVoice: "sharp, practical, build-in-public, slightly chaotic but credible",
    primaryGoal: "sell the automation tool and show operational competence",
    promotionChannels: ["gumroad", "devto", "linkedin", "x"],
    links: {
      gumroad: "",
      amazon: "",
      primary: "",
    },
    notes: [
      "Lead with usefulness and systems thinking.",
      "Good fit for build-in-public, workflow pain, and creator ops posts.",
    ],
  },
  {
    id: "gumroad-devtools",
    label: "Gumroad Devtools",
    lifecycleStatus: "live",
    category: "Digital products",
    productType: "Paid templates, prompts, and indie dev utility kits",
    audience: "makers who buy leverage, templates, and speed",
    brandVoice: "practical, scrappy, direct-response without sounding spammy",
    primaryGoal: "drive Gumroad conversions on smaller digital products",
    promotionChannels: ["gumroad", "x", "reddit", "linkedin"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/ai-powered-grad",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/ai-powered-grad",
    },
    notes: [
      "Show the problem solved and the speed gained.",
      "Use strong CTA language on Gumroad-facing posts.",
    ],
  },
  {
    id: "kawaii-coloring-series",
    label: "Kawaii Coloring Series",
    lifecycleStatus: "live",
    category: "Physical products",
    productType: "Cute coloring books and printable coloring pages",
    audience: "kawaii fans, cozy hobby shoppers, gift buyers, and younger creative audiences",
    brandVoice: "cute, sweet, playful, cozy, cheerful",
    primaryGoal: "sell the kawaii coloring line across Amazon, Pinterest, and visual channels",
    promotionChannels: ["amazon", "pinterest", "facebook", "instagram"],
    links: {
      gumroad: "",
      amazon: "https://www.amazon.com/-/es/Scary-Kawaii-Halloween-Coloring-Book/dp/B0DHDNTW87",
      primary: "https://www.amazon.com/-/es/Scary-Kawaii-Halloween-Coloring-Book/dp/B0DHDNTW87",
    },
    notes: [
      "Lead with cuteness, mood, giftability, and visual appeal.",
      "Great fit for Pinterest boards, reels, and gift-focused Amazon copy.",
    ],
  },
  {
    id: "goblin-self-care-coloring-book",
    label: "Goblin Self-Care Coloring Book",
    lifecycleStatus: "live",
    category: "Physical products",
    productType: "Funny, slightly unhinged self-care coloring book",
    audience: "burnt-out weird girls, goblin-mode adults, meme-friendly gift buyers",
    brandVoice: "chaotic, funny, self-aware, dark-cute, relatable",
    primaryGoal: "sell the goblin self-care book as a funny, giftable, niche personality product",
    promotionChannels: ["amazon", "facebook", "instagram", "pinterest"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/goblin-ritual-coloring-kit",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/goblin-ritual-coloring-kit",
    },
    notes: [
      "Lean into the joke, but keep the product clear and giftable.",
      "This should sound very different from the kawaii line.",
    ],
  },
  {
    id: "memoir-book",
    label: "Memoir",
    lifecycleStatus: "planned",
    category: "Books",
    productType: "Memoir and personal nonfiction book",
    audience: "readers who connect with personal story, healing, resilience, and transformation",
    brandVoice: "honest, intimate, reflective, literary but readable",
    primaryGoal: "build interest for the memoir and author identity across book-friendly channels",
    promotionChannels: ["amazon", "facebook", "instagram", "linkedin"],
    links: {
      gumroad: "",
      amazon: "",
      primary: "",
    },
    notes: [
      "Use personal truth and emotional clarity rather than hard-sell copy.",
      "Author identity matters more here than product-pitch energy.",
    ],
  },
  {
    id: "goblin-coloring-affirmations",
    label: "Goblin Core Coloring Affirmations",
    lifecycleStatus: "live",
    category: "Digital products",
    productType: "Printable goblin-core coloring affirmation pack",
    audience: "people who like weird affirmations, goblin humor, and printable self-care kits",
    brandVoice: "chaotic, funny, affirming, weirdly comforting",
    primaryGoal: "sell the printable affirmation pack on Gumroad",
    promotionChannels: ["gumroad", "facebook", "instagram", "pinterest"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/goblin-core-coloring-affirmations",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/goblin-core-coloring-affirmations",
    },
    notes: [
      "Sell the mood and the joke together.",
      "Works best as giftable, printable, low-friction self-care.",
    ],
  },
  {
    id: "ai-powered-grad",
    label: "AI Powered Grad",
    lifecycleStatus: "live",
    category: "Digital products",
    productType: "Graduation-themed AI prompt or resource product",
    audience: "students, grads, and buyers looking for AI-assisted graduation help",
    brandVoice: "clear, practical, encouraging, timely",
    primaryGoal: "drive Gumroad sales for the graduation offer",
    promotionChannels: ["gumroad", "facebook", "pinterest", "x"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/ai-powered-grad",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/ai-powered-grad",
    },
    notes: [
      "Lead with usefulness and urgency.",
      "This is more seasonal and practical than brand-heavy.",
    ],
  },
  {
    id: "prompt-storm",
    label: "100 Prompt Storm",
    lifecycleStatus: "live",
    category: "Digital products",
    productType: "Prompt pack for creators or builders",
    audience: "indie creators, writers, and prompt buyers looking for idea volume",
    brandVoice: "high-energy, practical, idea-rich",
    primaryGoal: "sell the prompt pack on Gumroad",
    promotionChannels: ["gumroad", "devto", "x", "reddit", "linkedin"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/100prompt-storm",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/100prompt-storm",
    },
    notes: [
      "Emphasize idea generation and momentum.",
      "Good fit for creator pain points and content block posts.",
    ],
  },
  {
    id: "product-strategy-25",
    label: "Product Strategy 25",
    lifecycleStatus: "live",
    category: "Digital products",
    productType: "Product strategy framework or guide",
    audience: "founders, indie hackers, and early-stage builders who need direction",
    brandVoice: "strategic, sharp, useful, no-fluff",
    primaryGoal: "sell the strategy guide on Gumroad",
    promotionChannels: ["gumroad", "devto", "linkedin", "x", "reddit"],
    links: {
      gumroad: "https://fleurdevie.gumroad.com/l/product-strategy-25",
      amazon: "",
      primary: "https://fleurdevie.gumroad.com/l/product-strategy-25",
    },
    notes: [
      "Lead with clarity, prioritization, and product thinking.",
      "Best framed as guidance that saves months of drift.",
    ],
  },
  {
    id: "buzzing-adventures-coloring-book",
    label: "Buzzing Adventures Coloring Book",
    lifecycleStatus: "live",
    category: "Physical products",
    productType: "Bee-themed coloring book",
    audience: "nature-loving kids, gift buyers, homeschoolers, and gentle hobby shoppers",
    brandVoice: "friendly, educational, playful, warm",
    primaryGoal: "sell the bee-themed coloring book on Amazon",
    promotionChannels: ["pinterest", "facebook"],
    links: {
      gumroad: "",
      amazon: "https://www.amazon.com/Buzzing-Adventures-Coloring-Explore-Beehives/dp/B0D9R6ZMPX",
      primary: "https://www.amazon.com/Buzzing-Adventures-Coloring-Explore-Beehives/dp/B0D9R6ZMPX",
    },
    notes: [
      "Lead with discovery, nature, and family-friendly creativity.",
      "Good fit for education-adjacent and giftable framing.",
    ],
  },
  {
    id: "reddit-product",
    label: "Reddit Product",
    lifecycleStatus: "planned",
    category: "Community tool",
    productType: "Tool or offer designed for Reddit-driven discovery",
    audience: "niche internet communities and problem-aware subreddit users",
    brandVoice: "transparent, useful, anti-marketing, context-aware",
    primaryGoal: "earn attention without getting treated like spam",
    promotionChannels: ["reddit", "x", "discord"],
    links: {
      gumroad: "",
      amazon: "",
      primary: "",
    },
    notes: [
      "Value first, promotion second.",
      "Assume subreddit rules matter more than brand voice.",
    ],
  },
];

export function getProductProfile(productId) {
  return productProfiles.find((profile) => profile.id === productId) || null;
}
